import { MapRendererContract } from "../MapRendererContract.js";

const VERTEX = `#version 300 es
precision highp float;
layout(location=0) in vec2 aPosition;
uniform vec2 uCameraCenter; uniform float uZoom; uniform float uPitch; uniform float uYaw;
void main(){vec2 p=aPosition-uCameraCenter;float y=radians(uYaw);float pch=radians(uPitch);vec2 r=vec2(p.x*cos(y)-p.y*sin(y),p.x*sin(y)+p.y*cos(y));r.y*=max(0.65,cos(pch));vec2 view=vec2(360.0,180.0)/max(uZoom,0.001);gl_Position=vec4(r/(view*0.5),0.0,1.0);}`;
const FRAGMENT = `#version 300 es
precision highp float;
uniform vec4 uColor;uniform vec4 uSelected;uniform vec4 uHovered;uniform float uSelectedId;uniform float uHoveredId;uniform float uProvinceId;out vec4 outColor;
void main(){vec4 c=uColor;if(abs(uProvinceId-uSelectedId)<0.5)c=mix(c,uSelected,0.68);else if(abs(uProvinceId-uHoveredId)<0.5)c=mix(c,uHovered,0.42);outColor=c;}`;
const PICK_FRAGMENT = `#version 300 es
precision highp float;
uniform float uProvinceId;out vec4 outColor;vec4 encode(float id){float r=mod(id,256.0);float g=mod(floor(id/256.0),256.0);float b=mod(floor(id/65536.0),256.0);return vec4(r,g,b,255.0)/255.0;}`;

export class BinaryMapRenderer extends MapRendererContract {
  constructor(canvas){super();this.canvas=canvas;this.state=null;this.camera={x:0,y:0,zoom:1,pitch:24,yaw:0};this.selected=0;this.hovered=0;this.frame=0;this.frameRequest=0;this.pickPixel=new Uint8Array(4);this.disposed=false;}
  initialize({assetSource}){if(this.disposed)throw new Error("Cannot initialize disposed renderer");if(!assetSource)return false;const gl=this.canvas.getContext("webgl2",{alpha:false,antialias:true,depth:false,stencil:false,preserveDrawingBuffer:false,powerPreference:"high-performance"});if(!gl)return false;const program=link(gl,VERTEX,FRAGMENT),pickProgram=link(gl,VERTEX,PICK_FRAGMENT),vao=gl.createVertexArray(),buffer=gl.createBuffer(),indexBuffer=gl.createBuffer(),fbo=makePickFbo(gl);if(!vao||!buffer||!indexBuffer)throw new Error("GPU geometry allocation failed");gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,assetSource.geometry,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,8,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,indexBuffer);const triangulation=buildTriangulatedIndexBuffer(assetSource);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,triangulation.indices,gl.STATIC_DRAW);gl.bindVertexArray(null);gl.bindBuffer(gl.ARRAY_BUFFER,null);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,null);this.state={gl,program,pickProgram,vao,buffer,indexBuffer,fbo,assetSource,draws:triangulation.draws,uniforms:uniforms(gl,program),pickUniforms:uniforms(gl,pickProgram)};return true;}
  setCamera(c){this.camera={...this.camera,...c};}
  setSelectedProvinceId(id){const index=this.state?.assetSource.indexOf(id)??-1;this.selected=index>=0?index+1:0;}
  setHoveredProvinceId(id){const index=this.state?.assetSource.indexOf(id)??-1;this.hovered=index>=0?index+1:0;}
  setHoveredRasterId(id){this.hovered=Number(id)>>>0;}
  lookupRasterId(id){const index=this.state?.assetSource.indexOf(id)??-1;return index>=0?index+1:0;}
  resize(w,h){const dpr=Math.min(globalThis.devicePixelRatio||1,2),W=Math.max(1,Math.round(Number(w)*dpr)),H=Math.max(1,Math.round(Number(h)*dpr));if(this.canvas.width!==W||this.canvas.height!==H){this.canvas.width=W;this.canvas.height=H;}}
  render(){if(this.disposed||!this.state)return;const{gl}=this.state;gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0.04,0.08,0.11,1);gl.clear(gl.COLOR_BUFFER_BIT);draw(this.state,this.camera,this.selected,this.hovered);this.frame+=1;}
  start(){if(this.disposed||this.frameRequest)return;const loop=()=>{if(this.disposed){this.frameRequest=0;return;}this.render();this.frameRequest=requestAnimationFrame(loop);};this.frameRequest=requestAnimationFrame(loop);}
  stop(){if(this.frameRequest)cancelAnimationFrame(this.frameRequest);this.frameRequest=0;}
  pick(x,y){if(this.disposed||!this.state)return null;const r=this.canvas.getBoundingClientRect();if(!r.width||!r.height)return null;const lx=(Number(x)-r.left)/r.width,ly=(Number(y)-r.top)/r.height;if(lx<0||lx>1||ly<0||ly>1)return null;const world=screenToWorld(lx,ly,this.camera);if(!world)return null;const{gl,fbo,pickProgram,pickUniforms,vao,assetSource,draws}=this.state;gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);gl.viewport(0,0,1,1);gl.useProgram(pickProgram);gl.bindVertexArray(vao);gl.uniform2f(pickUniforms.cameraCenter,world[0],world[1]);gl.uniform1f(pickUniforms.zoom,this.camera.zoom||1);gl.uniform1f(pickUniforms.pitch,this.camera.pitch||24);gl.uniform1f(pickUniforms.yaw,this.camera.yaw||0);for(const drawCall of draws){gl.uniform1f(pickUniforms.provinceId,drawCall.provinceId+1);gl.drawElements(gl.TRIANGLES,drawCall.indexCount,gl.UNSIGNED_INT,drawCall.indexOffset*4);}gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,this.pickPixel);gl.bindVertexArray(null);gl.bindFramebuffer(gl.FRAMEBUFFER,null);const id=this.pickPixel[0]|(this.pickPixel[1]<<8)|(this.pickPixel[2]<<16);return id>0?assetSource.getProvinceId(id-1)??null:null;}
  dispose(){if(this.disposed)return;this.disposed=true;this.stop();const s=this.state;this.state=null;if(!s)return;const gl=s.gl;gl.deleteVertexArray(s.vao);gl.deleteBuffer(s.buffer);gl.deleteBuffer(s.indexBuffer);gl.deleteFramebuffer(s.fbo);gl.deleteProgram(s.program);gl.deleteProgram(s.pickProgram);}
}

export function screenToWorld(localX,localY,camera={}){const zoom=Math.max(0.001,Number(camera.zoom)||1),pitch=(Number(camera.pitch)||24)*Math.PI/180,yaw=(Number(camera.yaw)||0)*Math.PI/180,cosPitch=Math.max(0.65,Math.cos(pitch)),ndcX=localX*2-1,ndcY=1-localY*2,viewX=360/zoom,viewY=180/zoom,rotatedX=ndcX*viewX*0.5,rotatedY=(ndcY*viewY*0.5)/cosPitch,worldX=rotatedX*Math.cos(yaw)+rotatedY*Math.sin(yaw)+(Number(camera.x)||0),worldY=-rotatedX*Math.sin(yaw)+rotatedY*Math.cos(yaw)+(Number(camera.y)||0);if(!Number.isFinite(worldX)||!Number.isFinite(worldY))return null;return[worldX,worldY];}

export function triangulatePolygon(polygon){const points=normalizePolygon(polygon);if(points.length<3)return new Uint32Array(0);const orientation=Math.sign(signedArea(points))||1;const remaining=points.map((_,index)=>index);const triangles=[];const maxIterations=points.length*points.length;let iterations=0;while(remaining.length>3&&iterations<maxIterations){let clipped=false;for(let i=0;i<remaining.length;i+=1){const prev=remaining[(i-1+remaining.length)%remaining.length],curr=remaining[i],next=remaining[(i+1)%remaining.length];if(!isConvex(points[prev],points[curr],points[next],orientation))continue;let contains=false;for(const candidate of remaining){if(candidate===prev||candidate===curr||candidate===next)continue;if(pointInTriangle(points[candidate],points[prev],points[curr],points[next])){contains=true;break;}}if(contains)continue;triangles.push(prev,curr,next);remaining.splice(i,1);clipped=true;break;}if(!clipped)return new Uint32Array(0);iterations+=1;}if(remaining.length===3){triangles.push(remaining[0],remaining[1],remaining[2]);return Uint32Array.from(triangles);}return new Uint32Array(0);}

function buildTriangulatedIndexBuffer(assetSource){const indices=[];const draws=[];for(let tileIndex=0;tileIndex<assetSource.tileCount;tileIndex+=1){const tile=assetSource.tileRecord(tileIndex);if(!tile||tile[1]<3)continue;const polygon=assetSource.geometryView(tile[0],tile[1]);const rawPoints=toPointArray(polygon);const localIndices=triangulatePolygon(rawPoints);if(tileIndex===1588){console.info("Historia AI triangulation diagnostic",{tileIndex,tile:Array.from(tile),pointCount:rawPoints.length,triangleIndexCount:localIndices.length,triangleCount:localIndices.length/3,firstPoints:rawPoints.slice(0,3),lastPoints:rawPoints.slice(-3)});}if(localIndices.length===0){const normalizedPoints=normalizePolygon(rawPoints);console.error("Historia AI triangulation failure diagnostic",{tileIndex,tile:Array.from(tile),rawPointCount:rawPoints.length,normalizedPointCount:normalizedPoints.length,normalizedSignedArea:signedArea(normalizedPoints),triangleIndexCount:localIndices.length,firstPoints:rawPoints.slice(0,5),lastPoints:rawPoints.slice(-5),normalizedFirstPoints:normalizedPoints.slice(0,5),normalizedLastPoints:normalizedPoints.slice(-5)});throw new Error(`Failed to triangulate province geometry tile ${tileIndex} (province index ${tile[2]})`);}const indexOffset=indices.length;for(const index of localIndices)indices.push(tile[0]+index);draws.push({indexOffset,indexCount:localIndices.length,provinceId:tile[2]});}return{indices:Uint32Array.from(indices),draws};}
function toPointArray(view){const points=[];for(let i=0;i<view.length;i+=2)points.push([view[i],view[i+1]]);return points;}
function normalizePolygon(polygon){const points=[];for(const point of polygon??[]){const x=Number(point?.[0]),y=Number(point?.[1]);if(!Number.isFinite(x)||!Number.isFinite(y))continue;const previous=points[points.length-1];if(previous&&samePoint(previous,[x,y]))continue;points.push([x,y]);}if(points.length>1&&samePoint(points[0],points[points.length-1]))points.pop();let changed=true;while(changed&&points.length>=3){changed=false;for(let i=0;i<points.length;i+=1){const prev=points[(i-1+points.length)%points.length],curr=points[i],next=points[(i+1)%points.length];if(Math.abs(cross(prev,curr,next))<=1e-12){points.splice(i,1);changed=true;break;}}}return points;}
function signedArea(points){let area=0;for(let i=0;i<points.length;i+=1){const a=points[i],b=points[(i+1)%points.length];area+=a[0]*b[1]-b[0]*a[1];}return area*0.5;}
function cross(a,b,c){return(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);}
function isConvex(a,b,c,orientation){return cross(a,b,c)*orientation>1e-12;}
function pointInTriangle(p,a,b,c){const ab=cross(a,b,p),bc=cross(b,c,p),ca=cross(c,a,p);const hasNegative=ab<-1e-12||bc<-1e-12||ca<-1e-12;const hasPositive=ab>1e-12||bc>1e-12||ca>1e-12;return!(hasNegative&&hasPositive)&&Math.abs(ab)>1e-12&&Math.abs(bc)>1e-12&&Math.abs(ca)>1e-12;}
function samePoint(a,b){return Math.abs(a[0]-b[0])<=1e-12&&Math.abs(a[1]-b[1])<=1e-12;}
function link(gl,v,f){const p=gl.createProgram(),vs=shader(gl,gl.VERTEX_SHADER,v),fs=shader(gl,gl.FRAGMENT_SHADER,f);if(!p||!vs||!fs)throw new Error("GPU program allocation failed");gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const e=gl.getProgramInfoLog(p)||"GPU program linking failed";gl.deleteProgram(p);throw new Error(e);}return p;}
function shader(gl,t,s){const x=gl.createShader(t);if(!x)throw new Error("GPU shader allocation failed");gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS)){const e=gl.getShaderInfoLog(x)||"GPU shader compilation failed";gl.deleteShader(x);throw new Error(e);}return x;}
function uniforms(gl,p){return{cameraCenter:gl.getUniformLocation(p,"uCameraCenter"),zoom:gl.getUniformLocation(p,"uZoom"),pitch:gl.getUniformLocation(p,"uPitch"),yaw:gl.getUniformLocation(p,"uYaw"),color:gl.getUniformLocation(p,"uColor"),selected:gl.getUniformLocation(p,"uSelected"),hovered:gl.getUniformLocation(p,"uHovered"),selectedId:gl.getUniformLocation(p,"uSelectedId"),hoveredId:gl.getUniformLocation(p,"uHoveredId"),provinceId:gl.getUniformLocation(p,"uProvinceId")};}
function makePickFbo(gl){const f=gl.createFramebuffer(),t=gl.createTexture();if(!f||!t)throw new Error("Picking target allocation failed");gl.bindTexture(gl.TEXTURE_2D,t);gl.texStorage2D(gl.TEXTURE_2D,1,gl.RGBA8,1,1);gl.bindFramebuffer(gl.FRAMEBUFFER,f);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,t,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error("Picking framebuffer incomplete");gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.bindTexture(gl.TEXTURE_2D,null);return f;}
function draw(s,c,selected,hovered){const gl=s.gl;gl.useProgram(s.program);gl.bindVertexArray(s.vao);gl.uniform2f(s.uniforms.cameraCenter,c.x||0,c.y||0);gl.uniform1f(s.uniforms.zoom,c.zoom||1);gl.uniform1f(s.uniforms.pitch,c.pitch||24);gl.uniform1f(s.uniforms.yaw,c.yaw||0);gl.uniform4f(s.uniforms.selected,0.95,0.78,0.18,1);gl.uniform4f(s.uniforms.hovered,1,1,1,1);gl.uniform1f(s.uniforms.selectedId,selected);gl.uniform1f(s.uniforms.hoveredId,hovered);for(const drawCall of s.draws){const h=hashColor(s.assetSource.getProvinceId(drawCall.provinceId));gl.uniform4f(s.uniforms.color,h[0],h[1],h[2],1);gl.uniform1f(s.uniforms.provinceId,drawCall.provinceId+1);gl.drawElements(gl.TRIANGLES,drawCall.indexCount,gl.UNSIGNED_INT,drawCall.indexOffset*4);}gl.bindVertexArray(null);}
function hashColor(id){let x=(Number(id)>>>0)*2654435761>>>0;return[((x&255)/255)*0.65+0.2,(((x>>>8)&255)/255)*0.65+0.2,(((x>>>16)&255)/255)*0.65+0.2];}

export default BinaryMapRenderer;
