import { WORLD_LAND_POLYGONS } from "../../physical/WorldPhysicalAtlas.js";
import { ANATOLIA_PHYSICAL_ATLAS_RUNTIME } from "../../data/AnatoliaPhysicalAtlasRuntime.js";
import { triangulatePolygon } from "./BinaryMapRenderer.js";
import { TerrainGpuRenderer } from "../terrain/TerrainGpuRenderer.js";
import { loadTerrainManifest, loadTerrainTileAsset } from "../terrain/TerrainAssetLoader.js";
import { planTerrainStreaming } from "../terrain/TerrainStreaming.js";
import { buildTerrainMvp } from "../terrain/TerrainCameraMath.js";

const VERTEX=`#version 300 es
precision highp float;layout(location=0) in vec2 aPosition;uniform mat4 uMvp;uniform float uElevationOffset;void main(){gl_Position=uMvp*vec4(aPosition,uElevationOffset,1.0);}`;
const FRAGMENT=`#version 300 es
precision highp float;uniform vec4 uColor;out vec4 outColor;void main(){outColor=uColor;}`;
const WORLD_LAND=[0.16,0.20,0.17,1],LAKE=[0.10,0.31,0.37,0.92],RIVER=[0.30,0.61,0.66,0.86],RIVER_UNDER=[0.06,0.16,0.19,0.75],COAST=[0.58,0.70,0.67,0.72];
const PHYSICAL_ELEVATION_OFFSETS=Object.freeze({land:0,lake:0.02,riverUnder:0.02,river:0.03,coast:0.04});

/** Physical geography compositor. Land is the mask authority; terrain is a DEM-driven relief pass above it. */
export class ProductionPhysicalMapLayer{
 constructor(){this.state=null;this.terrain=null;this.terrainManifest=null;this.terrainById=new Map();this.terrainPending=new Map();this.disposed=false;}
 initialize(gl,{terrainManifestUrl="/assets/terrain/manifest.json"}={}){if(this.disposed)throw new Error("Cannot initialize disposed physical layer");const program=link(gl,VERTEX,FRAGMENT);this.terrain=new TerrainGpuRenderer(gl);this.state={gl,program,fill:createGeometry(gl,buildPolygonGeometry(WORLD_LAND_POLYGONS)),coast:createGeometry(gl,buildLineGeometry(WORLD_LAND_POLYGONS)),lakes:createGeometry(gl,buildPolygonGeometry((ANATOLIA_PHYSICAL_ATLAS_RUNTIME.lakes??[]).map(f=>f.coordinates))),riversUnder:createGeometry(gl,buildLineGeometry(ANATOLIA_PHYSICAL_ATLAS_RUNTIME.rivers??[],true)),rivers:createGeometry(gl,buildLineGeometry(ANATOLIA_PHYSICAL_ATLAS_RUNTIME.rivers??[])),uniforms:{color:gl.getUniformLocation(program,"uColor"),mvp:gl.getUniformLocation(program,"uMvp"),elevationOffset:gl.getUniformLocation(program,"uElevationOffset")}};this.terrainManifestPromise=loadTerrainManifest(terrainManifestUrl).then((manifest)=>{if(!this.disposed)this.terrainManifest=manifest;}).catch((error)=>{if(!this.disposed&&import.meta.env?.DEV)console.warn("[Terrain] DEM manifest unavailable",error);});return true;}
 render(camera,width,height){if(this.disposed||!this.state)return;const{gl}=this.state;const mvp=buildTerrainMvp(camera,width,height);gl.viewport(0,0,width,height);gl.clear(gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.disable(gl.BLEND);
   gl.depthMask(false);
   this.bindPhysicalProgram(mvp);drawGeometry(this.state,this.state.fill,WORLD_LAND,PHYSICAL_ELEVATION_OFFSETS.land);
   this.updateTerrainStreaming(camera);
   gl.depthMask(true);
   this.terrain?.draw(camera,width,height);
   this.bindPhysicalProgram(mvp);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthFunc(gl.LEQUAL);gl.depthMask(false);
   drawGeometry(this.state,this.state.lakes,LAKE,PHYSICAL_ELEVATION_OFFSETS.lake);drawGeometry(this.state,this.state.riversUnder,RIVER_UNDER,PHYSICAL_ELEVATION_OFFSETS.riverUnder);drawGeometry(this.state,this.state.rivers,RIVER,PHYSICAL_ELEVATION_OFFSETS.river);drawGeometry(this.state,this.state.coast,COAST,PHYSICAL_ELEVATION_OFFSETS.coast);
   gl.depthMask(true);gl.disable(gl.BLEND);gl.bindVertexArray(null);
 }
 bindPhysicalProgram(mvp){const{gl,program,uniforms}=this.state;gl.useProgram(program);gl.uniformMatrix4fv(uniforms.mvp,false,mvp);}
 updateTerrainStreaming(camera){if(!this.terrainManifest||!this.terrain)return;const zoom=Math.max(1,Number(camera?.zoom)||1),pitch=(Number(camera?.pitch)||0)*Math.PI/180,viewWidth=360/zoom,viewHeight=180/zoom/Math.max(0.65,Math.cos(pitch)),viewBounds={minX:(Number(camera?.x)||0)-viewWidth*0.5,minY:(Number(camera?.y)||0)-viewHeight*0.5,maxX:(Number(camera?.x)||0)+viewWidth*0.5,maxY:(Number(camera?.y)||0)+viewHeight*0.5};let plan;try{plan=planTerrainStreaming({viewBounds,cameraDistance:360/zoom,maxTiles:16});}catch{return;}const records=new Map((this.terrainManifest.tiles??[]).map((record)=>[record.id,record]));const wanted=new Set();for(const tile of plan.tiles){const record=records.get(tile.id);if(!record)continue;wanted.add(record.id);if(this.terrainById.has(record.id)||this.terrainPending.has(record.id))continue;const promise=loadTerrainTileAsset(record).then((asset)=>{if(this.disposed)return;this.terrain.uploadTile(record.id,asset,record.bounds,record.dataBounds);this.terrainById.set(record.id,asset);this.terrainPending.delete(record.id);}).catch((error)=>{this.terrainPending.delete(record.id);if(import.meta.env?.DEV)console.warn(`[Terrain] tile ${record.id} failed`,error);});this.terrainPending.set(record.id,promise);}for(const id of this.terrainById.keys())if(!wanted.has(id)){this.terrain.removeTile(id);this.terrainById.delete(id);}}
 dispose(){if(this.disposed)return;this.disposed=true;const state=this.state;this.state=null;this.terrainManifest=null;this.terrainPending.clear();this.terrainById.clear();this.terrain?.dispose();this.terrain=null;if(!state)return;state.gl.deleteProgram(state.program);for(const key of ["fill","coast","lakes","riversUnder","rivers"])destroyGeometry(state.gl,state[key]);}}
function buildPolygonGeometry(polygons){const vertices=[],indices=[];for(const polygon of polygons??[]){if(!Array.isArray(polygon)||polygon.length<3)continue;const triangles=triangulatePolygon(polygon);if(!triangles.length)continue;const base=vertices.length/2;for(const point of polygon)vertices.push(Number(point?.[0]),Number(point?.[1]));for(const index of triangles)indices.push(base+index);}return{vertices:Float32Array.from(vertices),indices:Uint32Array.from(indices)};}
function buildLineGeometry(features,simplified=false){const vertices=[];for(const feature of features??[]){const coordinates=feature?.coordinates??feature?.rings?.[0]??[];if(!Array.isArray(coordinates)||coordinates.length<2)continue;const points=simplified?simplifyLine(coordinates,2):coordinates;for(let i=1;i<points.length;i+=1){const a=points[i-1],b=points[i];if(!a||!b)continue;vertices.push(Number(a[0]),Number(a[1]),Number(b[0]),Number(b[1]));}}return{vertices:Float32Array.from(vertices),indices:null};}
function simplifyLine(points,stride){if(points.length<=2)return points;const result=[points[0]];for(let i=stride;i<points.length-1;i+=stride)result.push(points[i]);result.push(points[points.length-1]);return result;}
function createGeometry(gl,data){const vao=gl.createVertexArray(),buffer=gl.createBuffer(),indexBuffer=data.indices?gl.createBuffer():null;if(!vao||!buffer||(data.indices&&!indexBuffer))throw new Error("Physical GPU geometry allocation failed");gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data.vertices,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,8,0);if(indexBuffer){gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,indexBuffer);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,data.indices,gl.STATIC_DRAW);}gl.bindVertexArray(null);gl.bindBuffer(gl.ARRAY_BUFFER,null);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,null);return{vao,buffer,indexBuffer,count:data.indices?.length??data.vertices.length/2};}
function drawGeometry(state,geometry,color,elevationOffset=0){if(!geometry?.count)return;const{gl,uniforms}=state;gl.bindVertexArray(geometry.vao);gl.uniform4fv(uniforms.color,color);gl.uniform1f(uniforms.elevationOffset,elevationOffset);if(geometry.indexBuffer)gl.drawElements(gl.TRIANGLES,geometry.count,gl.UNSIGNED_INT,0);else gl.drawArrays(gl.LINES,0,geometry.count);}
function destroyGeometry(gl,geometry){if(!geometry)return;gl.deleteVertexArray(geometry.vao);gl.deleteBuffer(geometry.buffer);if(geometry.indexBuffer)gl.deleteBuffer(geometry.indexBuffer);}
function link(gl,vertexSource,fragmentSource){const program=gl.createProgram(),vertex=compile(gl,gl.VERTEX_SHADER,vertexSource),fragment=compile(gl,gl.FRAGMENT_SHADER,fragmentSource);gl.attachShader(program,vertex);gl.attachShader(program,fragment);gl.linkProgram(program);gl.deleteShader(vertex);gl.deleteShader(fragment);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){const error=gl.getProgramInfoLog(program)||"Physical GPU program linking failed";gl.deleteProgram(program);throw new Error(error);}return program;}
function compile(gl,type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const error=gl.getShaderInfoLog(shader)||"Physical GPU shader compilation failed";gl.deleteShader(shader);throw new Error(error);}return shader;}
