/** Deterministic indexed GPU province geometry compiler. HMAP/GIS remains authoritative. */
const EPSILON = 1e-10;
const COLLINEAR_EPSILON = 1e-12;
const MAX_LOD0_VERTICES = 512;
const DEFAULT_MAX_OPERATIONS = 250000;

const cross = (a,b,c) => (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const signedArea = (ring) => { let s=0; for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length];s+=a[0]*b[1]-b[0]*a[1];} return s/2; };
const samePoint=(a,b)=>Math.abs(a[0]-b[0])<=EPSILON&&Math.abs(a[1]-b[1])<=EPSILON;
const orient=(a,b,c)=>{const v=cross(a,b,c); if(Math.abs(v)<=EPSILON)return 0; return v>0?1:-1;};
const onSegment=(a,b,p)=>orient(a,b,p)===0&&p[0]>=Math.min(a[0],b[0])-EPSILON&&p[0]<=Math.max(a[0],b[0])+EPSILON&&p[1]>=Math.min(a[1],b[1])-EPSILON&&p[1]<=Math.max(a[1],b[1])+EPSILON;
function strictCross(a,b,c,d){const abC=orient(a,b,c),abD=orient(a,b,d),cdA=orient(c,d,a),cdB=orient(c,d,b);return abC!==0&&abD!==0&&cdA!==0&&cdB!==0&&abC!==abD&&cdA!==cdB;}
function operation(state,n=1){state.operations+=n;if(state.operations>state.maxOperations){const e=new Error(`GPU triangulation operation budget exceeded; operations=${state.operations}; limit=${state.maxOperations}`);e.code='GPU_TRIANGULATION_BUDGET';throw e;}}

export function normalizeRing(ring){
 const out=[];
 for(const point of Array.isArray(ring)?ring:[]){if(!Array.isArray(point)||point.length<2)continue;const p=[Number(point[0]),Number(point[1])];if(!Number.isFinite(p[0])||!Number.isFinite(p[1]))continue;if(!out.length||!samePoint(out[out.length-1],p))out.push(p);}
 if(out.length>1&&samePoint(out[0],out[out.length-1]))out.pop();
 let changed=true,guard=0;
 while(changed&&out.length>3&&guard++<out.length*2){changed=false;for(let i=0;i<out.length&&out.length>3;i++){const a=out[(i-1+out.length)%out.length],b=out[i],c=out[(i+1)%out.length];const scale=Math.max(1,Math.hypot(c[0]-a[0],c[1]-a[1]));if(Math.abs(cross(a,b,c))<=COLLINEAR_EPSILON*scale){out.splice(i,1);changed=true;i--;}}}
 return out;
}
function isSimple(ring,state){for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length];for(let j=i+1;j<ring.length;j++){if(j===i+1||(i===0&&j===ring.length-1))continue;operation(state);if(strictCross(a,b,ring[j],ring[(j+1)%ring.length]))return false;}}return true;}
function pointInPolygon(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(onSegment(a,b,p))return true;if((a[1]>p[1])!==(b[1]>p[1])){const x=((b[0]-a[0])*(p[1]-a[1]))/((b[1]-a[1])||EPSILON)+a[0];if(p[0]<x)inside=!inside;}}return inside;}
function diagonalClear(ring,ia,ib,state){const a=ring[ia],b=ring[ib],mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];if(!pointInPolygon(mid,ring))return false;for(let i=0;i<ring.length;i++){const j=(i+1)%ring.length;if(i===ia||i===ib||j===ia||j===ib)continue;operation(state);if(strictCross(a,b,ring[i],ring[j]))return false;}return true;}
function strictlyInsideTriangle(p,a,b,c){const x=cross(a,b,p),y=cross(b,c,p),z=cross(c,a,p);return(x>EPSILON&&y>EPSILON&&z>EPSILON)||(x<-EPSILON&&y<-EPSILON&&z<-EPSILON);}
function isConvex(ring){let sign=0;for(let i=0;i<ring.length;i++){const v=cross(ring[i],ring[(i+1)%ring.length],ring[(i+2)%ring.length]);if(Math.abs(v)<=EPSILON)continue;const s=v>0?1:-1;if(sign&&sign!==s)return false;sign=s;}return sign!==0;}
function fan(ring){const ids=Array.from({length:ring.length},(_,i)=>i);if(signedArea(ring)<0)ids.reverse();const out=[];for(let i=1;i<ids.length-1;i++)out.push(ids[0],ids[i],ids[i+1]);return out;}
function earClip(ring,state){const reversed=signedArea(ring)<0;const points=reversed?ring.slice().reverse():ring.slice();const source=reversed?ring.map((_,i)=>ring.length-1-i):ring.map((_,i)=>i);const ids=Array.from({length:points.length},(_,i)=>i);const out=[];let guard=0;const guardLimit=points.length*points.length*4;while(ids.length>3){if(++guard>guardLimit){const e=new Error(`GPU triangulation guard exceeded; vertices=${points.length}`);e.code='GPU_TRIANGULATION_GUARD';throw e;}let found=-1;for(let i=0;i<ids.length;i++){const ia=ids[(i-1+ids.length)%ids.length],ib=ids[i],ic=ids[(i+1)%ids.length];const a=points[ia],b=points[ib],c=points[ic];if(cross(a,b,c)<=EPSILON)continue;if(!diagonalClear(points,ia,ic,state))continue;let blocked=false;for(const k of ids){if(k===ia||k===ib||k===ic)continue;operation(state);if(strictlyInsideTriangle(points[k],a,b,c)){blocked=true;break;}}if(!blocked){found=i;break;}}if(found<0)return null;const ia=ids[(found-1+ids.length)%ids.length],ib=ids[found],ic=ids[(found+1)%ids.length];out.push(source[ia],source[ib],source[ic]);ids.splice(found,1);}out.push(source[ids[0]],source[ids[1]],source[ids[2]]);return out;}
export function triangulateRing(ring,context={}){const points=normalizeRing(ring);if(points.length<3)return [];const state={operations:0,maxOperations:Number(context.maxOperations??DEFAULT_MAX_OPERATIONS)};if(!Number.isFinite(state.maxOperations)||state.maxOperations<1)throw new Error('Invalid GPU triangulation operation budget');const area=signedArea(points);if(Math.abs(area)<=EPSILON){const e=new Error(`Degenerate province ring${context.provinceId?` province=${context.provinceId}`:''}${context.lod===undefined?'':` lod=${context.lod}`}`);e.code='GPU_DEGENERATE_RING';throw e;}if(!isSimple(points,state)){const e=new Error(`GPU topology is self-intersecting${context.provinceId?` province=${context.provinceId}`:''}${context.polygonIndex===undefined?'':` polygon=${context.polygonIndex}`}${context.lod===undefined?'':` lod=${context.lod}`}; vertices=${points.length}; operations=${state.operations}`);e.code='GPU_SELF_INTERSECTION';throw e;}if(isConvex(points))return fan(points);const result=earClip(points,state);if(!result){const e=new Error(`GPU triangulation failed${context.provinceId?` province=${context.provinceId}`:''}; vertices=${points.length}; operations=${state.operations}`);e.code='GPU_TRIANGULATION_FAILED';throw e;}return result;}
function canRemove(ring,index,state){if(ring.length<=3)return false;const prev=(index-1+ring.length)%ring.length,next=(index+1)%ring.length;const replacement=[...ring.slice(0,index),...ring.slice(index+1)];if(!diagonalClear(ring,prev,next,state))return false;const before=Math.abs(signedArea(ring)),after=Math.abs(signedArea(replacement));return before>EPSILON&&after>EPSILON&&after/before>=0.985;}
function simplifyRing(ring,target){let current=normalizeRing(ring);if(current.length<=target||target<3)return current;let cursor=0;while(current.length>target){let removed=false;const count=current.length;for(let n=0;n<count;n++){const i=(cursor+n)%current.length;const state={operations:0,maxOperations:Math.max(50000,current.length*current.length*4)};if(canRemove(current,i,state)){current.splice(i,1);cursor=i%current.length;removed=true;break;}}if(!removed)break;}return current;}
export function buildLodRings(ring,levels=[1,0.5,0.25,0.125]){const source=normalizeRing(ring);return levels.map((factor,level)=>{let target=level===0?Math.min(MAX_LOD0_VERTICES,source.length):Math.max(3,Math.min(MAX_LOD0_VERTICES,Math.round(source.length*factor)));while(target>=3){const candidate=simplifyRing(source,target);if(candidate.length>=3){try{triangulateRing(candidate,{maxOperations:Math.max(DEFAULT_MAX_OPERATIONS,candidate.length*candidate.length*8)});return candidate;}catch(error){if(!(error instanceof Error))throw error;}}if(target===3)break;target=Math.max(3,Math.floor(target*0.85));}return source;});}
function quantizedKey(p,scale){return `${Math.round(p[0]*scale)},${Math.round(p[1]*scale)}`;}
export function buildIndexedProvincePack(entries=[],options={}){const tileSize=Number(options.tileSize??10),quantization=Number(options.quantization??1e6);if(!Number.isFinite(tileSize)||tileSize<=0)throw new Error('Invalid tile size');if(!Number.isFinite(quantization)||quantization<=0)throw new Error('Invalid quantization');const vertices=[],indices=[],vertexMap=new Map(),provinces=[],tiles=new Map();const getVertex=p=>{const key=quantizedKey(p,quantization),old=vertexMap.get(key);if(old!==undefined)return old;const i=vertices.length/2;vertices.push(p[0],p[1]);vertexMap.set(key,i);return i;};entries.forEach((entry,provinceIndex)=>{const id=String(entry?.province?.id??entry?.id??provinceIndex),polygons=entry?.geometry?.polygons??entry?.polygons??[],lodRanges=[];let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(let lod=0;lod<4;lod++){const firstIndex=indices.length;polygons.forEach((polygon,polygonIndex)=>{const ring=buildLodRings(polygon)[lod];if(ring.length<3)return;ring.forEach(p=>{minX=Math.min(minX,p[0]);minY=Math.min(minY,p[1]);maxX=Math.max(maxX,p[0]);maxY=Math.max(maxY,p[1]);});const triangles=triangulateRing(ring,{provinceId:id,polygonIndex,lod});triangles.forEach(localIndex=>indices.push(getVertex(ring[localIndex])));});const indexCount=indices.length-firstIndex;if(indexCount%3!==0)throw new Error(`LOD${lod} range is not triangle aligned for ${id}`);lodRanges.push(Object.freeze({firstIndex,indexCount}));}const bounds=Number.isFinite(minX)?Object.freeze({minX,minY,maxX,maxY}):null;provinces.push(Object.freeze({provinceIndex,provinceId:id,bounds,lodRanges:Object.freeze(lodRanges)}));if(bounds){const minTX=Math.floor(bounds.minX/tileSize),maxTX=Math.floor(bounds.maxX/tileSize),minTY=Math.floor(bounds.minY/tileSize),maxTY=Math.floor(bounds.maxY/tileSize);for(let x=minTX;x<=maxTX;x++)for(let y=minTY;y<=maxTY;y++){const key=`${x}:${y}`;if(!tiles.has(key))tiles.set(key,{tileId:key,x,y,provinceIndices:[]});tiles.get(key).provinceIndices.push(provinceIndex);}}});return Object.freeze({version:2,tileSize,quantization,vertices:new Float32Array(vertices),indices:new Uint32Array(indices),provinces:Object.freeze(provinces),tiles:Object.freeze([...tiles.values()].map(t=>Object.freeze({...t,provinceIndices:Object.freeze([...new Set(t.provinceIndices)].sort((a,b)=>a-b))}))) });}
