/** Bounded deterministic GPU province pack builder. HMAP/GIS remains authoritative. */
const EPSILON=1e-10;
const MAX_LOD0_VERTICES=512;
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const area=(r)=>{let s=0;for(let i=0;i<r.length;i++){const a=r[i],b=r[(i+1)%r.length];s+=a[0]*b[1]-b[0]*a[1];}return s/2;};
const same=(a,b)=>Math.abs(a[0]-b[0])<=EPSILON&&Math.abs(a[1]-b[1])<=EPSILON;
export function normalizeRing(ring){const out=[];for(const p of Array.isArray(ring)?ring:[]){if(!Array.isArray(p)||p.length<2)continue;const q=[Number(p[0]),Number(p[1])];if(!Number.isFinite(q[0])||!Number.isFinite(q[1]))continue;if(out.length&&same(out[out.length-1],q))continue;out.push(q);}if(out.length>1&&same(out[0],out[out.length-1]))out.pop();let changed=true;while(changed&&out.length>3){changed=false;for(let i=0;i<out.length&&out.length>3;i++){const a=out[(i-1+out.length)%out.length],b=out[i],c=out[(i+1)%out.length];const scale=Math.max(1,Math.hypot(b[0]-a[0],b[1]-a[1]),Math.hypot(c[0]-b[0],c[1]-b[1]));if(Math.abs(cross(a,b,c))<=1e-10*scale){out.splice(i,1);changed=true;i--;}}}return out;}
function orient(a,b,c){const v=cross(a,b,c);return Math.abs(v)<=EPSILON?0:v>0?1:-1;}
function onSeg(a,b,p){return orient(a,b,p)===0&&p[0]>=Math.min(a[0],b[0])-EPSILON&&p[0]<=Math.max(a[0],b[0])+EPSILON&&p[1]>=Math.min(a[1],b[1])-EPSILON&&p[1]<=Math.max(a[1],b[1])+EPSILON;}
function sameEndpoint(a,b,c,d){return(same(a,c)||same(a,d)||same(b,c)||same(b,d));}
function properCross(a,b,c,d){const ab1=orient(a,b,c),ab2=orient(a,b,d),cd1=orient(c,d,a),cd2=orient(c,d,b);if(ab1&&ab2&&cd1&&cd2)return ab1!==ab2&&cd1!==cd2;if(ab1===0&&ab2===0&&cd1===0&&cd2===0){const axis=Math.abs(a[0]-b[0])>=Math.abs(a[1]-b[1])?'x':'y';const amin=axis==='x'?Math.min(a[0],b[0]):Math.min(a[1],b[1]);const amax=axis==='x'?Math.max(a[0],b[0]):Math.max(a[1],b[1]);const cmin=axis==='x'?Math.min(c[0],d[0]):Math.min(c[1],d[1]);const cmax=axis==='x'?Math.max(c[0],d[0]):Math.max(c[1],d[1]);const lo=Math.max(amin,cmin),hi=Math.min(amax,cmax);return hi-lo>EPSILON&&!sameEndpoint(a,b,c,d);}if(ab1===0&&onSeg(a,b,c))return !same(c,a)&&!same(c,b);if(ab2===0&&onSeg(a,b,d))return !same(d,a)&&!same(d,b);if(cd1===0&&onSeg(c,d,a))return !same(a,c)&&!same(a,d);if(cd2===0&&onSeg(c,d,b))return !same(b,c)&&!same(b,d);return false;}
function simple(r){for(let i=0;i<r.length;i++){const a=r[i],b=r[(i+1)%r.length];for(let j=i+1;j<r.length;j++){if(j===i||j===(i+1)%r.length||(i===0&&j===r.length-1))continue;const c=r[j],d=r[(j+1)%r.length];if(properCross(a,b,c,d))return false;}}return true;}
function convex(r){if(r.length<3)return false;let sign=0;for(let i=0;i<r.length;i++){const v=orient(r[i],r[(i+1)%r.length],r[(i+2)%r.length]);if(!v)continue;if(!sign)sign=v;else if(sign!==v)return false;}return true;}
function strictInside(p,a,b,c){const x=cross(a,b,p),y=cross(b,c,p),z=cross(c,a,p);return(x>EPSILON&&y>EPSILON&&z>EPSILON)||(x<-EPSILON&&y<-EPSILON&&z<-EPSILON);}
function diagonalClear(r,ids,a,c){for(let i=0;i<ids.length;i++){const u=ids[i],v=ids[(i+1)%ids.length];if(u===a||u===c||v===a||v===c)continue;if(properCross(r[a],r[c],r[u],r[v]))return false;}const m=[(r[a][0]+r[c][0])/2,(r[a][1]+r[c][1])/2];let inside=false;for(let i=0,j=ids.length-1;i<ids.length;j=i++){const p=r[ids[i]],q=r[ids[j]];if(onSeg(p,q,m))return true;if((p[1]>m[1])!==(q[1]>m[1])&&m[0]<((q[0]-p[0])*(m[1]-p[1]))/((q[1]-p[1])||EPSILON)+p[0])inside=!inside;}return inside;}
function earClip(r){if(r.length<3)return null;if(convex(r)){const ids=Array.from({length:r.length},(_,i)=>i);if(area(r)<0)ids.reverse();const out=[];for(let i=1;i<ids.length-1;i++)out.push(ids[0],ids[i],ids[i+1]);return out;}const ids=Array.from({length:r.length},(_,i)=>i);if(area(r)<0)ids.reverse();const rem=ids.slice(),out=[];let guard=0,maxGuard=r.length*r.length*2;while(rem.length>3&&guard++<maxGuard){let found=-1;for(let i=0;i<rem.length;i++){const a=rem[(i-1+rem.length)%rem.length],b=rem[i],c=rem[(i+1)%rem.length];if(cross(r[a],r[b],r[c])<=EPSILON||!diagonalClear(r,rem,a,c))continue;let blocked=false;for(const k of rem)if(k!==a&&k!==b&&k!==c&&strictInside(r[k],r[a],r[b],r[c])){blocked=true;break;}if(!blocked){found=i;break;}}if(found<0)return null;const a=rem[(found-1+rem.length)%rem.length],b=rem[found],c=rem[(found+1)%rem.length];out.push(a,b,c);rem.splice(found,1);}if(rem.length===3&&cross(r[rem[0]],r[rem[1]],r[rem[2]])>EPSILON)out.push(...rem);return out.length===(r.length-2)*3?out:null;}
function boundedSimplify(r,target){r=normalizeRing(r);if(r.length<=target||target<3)return r;const step=r.length/target;for(let pass=0;pass<3;pass++){const out=[];for(let i=0;i<target;i++)out.push(r[Math.min(r.length-1,Math.floor(i*step))]);const n=normalizeRing(out);if(n.length>=3&&simple(n)&&Math.abs(area(n))>EPSILON){const tris=earClip(n);if(tris&&Math.abs(Math.abs(area(n))-Math.abs(area(r)))/Math.max(Math.abs(area(r)),EPSILON)<0.35)return n;}target=Math.max(3,Math.floor(target*0.75));}return r;}
export function triangulateRing(ring,context={}){const r=normalizeRing(ring);if(r.length<3)return [];if(Math.abs(area(r))<=EPSILON)throw new Error(`Degenerate province ring${context.provinceId?` for ${context.provinceId}`:''}`);if(!simple(r)&&r.length<=MAX_LOD0_VERTICES)throw new Error(`Self-intersecting province ring${context.provinceId?` for ${context.provinceId}`:''}`);const result=earClip(r);if(!result)throw new Error(`Province triangulation failed${context.provinceId?` province=${context.provinceId}`:''}${context.lod===undefined?'':` lod=${context.lod}`}; vertices=${r.length}`);return result;}
function simplifyRing(ring,target){const r=normalizeRing(ring);return boundedSimplify(r,Math.min(r.length,target));}
export function buildLodRings(ring,levels=[1,.5,.25,.125]){const r=normalizeRing(ring);return levels.map((factor,level)=>{const target=Math.min(r.length,Math.max(level===0?Math.min(MAX_LOD0_VERTICES,r.length):3,Math.round(r.length*factor)));return simplifyRing(r,target);});}
const qkey=(p,s)=>`${Math.round(p[0]*s)},${Math.round(p[1]*s)}`;
export function buildIndexedProvincePack(entries=[],options={}){const tileSize=Number(options.tileSize??10),quantization=Number(options.quantization??1e6);if(!Number.isFinite(tileSize)||tileSize<=0)throw new Error('Invalid tile size');if(!Number.isFinite(quantization)||quantization<=0)throw new Error('Invalid quantization');const vertices=[],indices=[],map=new Map(),provinces=[],tiles=new Map();const vertex=p=>{const k=qkey(p,quantization),old=map.get(k);if(old!==undefined)return old;const i=vertices.length/2;vertices.push(p[0],p[1]);map.set(k,i);return i;};entries.forEach((entry,provinceIndex)=>{const id=String(entry?.province?.id??entry?.id??provinceIndex),polygons=entry?.geometry?.polygons??entry?.polygons??[],ranges=[];let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(let lod=0;lod<4;lod++){const firstIndex=indices.length;for(const polygon of polygons){const ring=buildLodRings(polygon)[lod];if(ring.length<3)continue;for(const p of ring){minX=Math.min(minX,p[0]);minY=Math.min(minY,p[1]);maxX=Math.max(maxX,p[0]);maxY=Math.max(maxY,p[1]);}for(const i of triangulateRing(ring,{provinceId:id,lod}))indices.push(vertex(ring[i]));}const indexCount=indices.length-firstIndex;if(indexCount%3)throw new Error(`LOD${lod} range is not triangle aligned for ${id}`);ranges.push(Object.freeze({firstIndex,indexCount}));}const bounds=Number.isFinite(minX)?Object.freeze({minX,minY,maxX,maxY}):null;provinces.push(Object.freeze({provinceIndex,provinceId:id,bounds,lodRanges:Object.freeze(ranges)}));if(bounds){for(let x=Math.floor(bounds.minX/tileSize);x<=Math.floor(bounds.maxX/tileSize);x++)for(let y=Math.floor(bounds.minY/tileSize);y<=Math.floor(bounds.maxY/tileSize);y++){const k=`${x}:${y}`;if(!tiles.has(k))tiles.set(k,{tileId:k,x,y,provinceIndices:[]});tiles.get(k).provinceIndices.push(provinceIndex);}}});return Object.freeze({version:2,tileSize,quantization,vertices:new Float32Array(vertices),indices:new Uint32Array(indices),provinces:Object.freeze(provinces),tiles:Object.freeze([...tiles.values()].map(t=>Object.freeze({...t,provinceIndices:Object.freeze([...new Set(t.provinceIndices)].sort((a,b)=>a-b))})))})}
