/** WebGL2 indexed renderer. Province identity is a draw-level uniform, so shared vertices remain truly indexed. */
export function createIndexedProvinceRenderer(canvas) {
  const gl=canvas?.getContext?.("webgl2",{alpha:true,antialias:true,depth:false,stencil:false}); if(!gl)throw new Error("Historia AI indexed province renderer requires WebGL2");
  const vertex=compile(gl,gl.VERTEX_SHADER,`#version 300 es
layout(location=0) in vec2 a_position; uniform vec2 u_camera; uniform vec2 u_halfExtent; void main(){vec2 p=(a_position-u_camera)/u_halfExtent;gl_Position=vec4(p.x,-p.y,0.0,1.0);}`);
  const fragment=compile(gl,gl.FRAGMENT_SHADER,`#version 300 es
precision highp float; uniform uint u_province; uniform uint u_selected; uniform vec4 u_selectedColor; out vec4 outColor; void main(){outColor=u_province==u_selected?u_selectedColor:vec4(0.42,0.45,0.35,1.0);}`);
  const pickFragment=compile(gl,gl.FRAGMENT_SHADER,`#version 300 es
precision highp int; uniform uint u_province; layout(location=0) out uint outId; void main(){outId=u_province;}`);
  const program=link(gl,vertex,fragment); const pickProgram=link(gl,vertex,pickFragment); gl.deleteShader(vertex);gl.deleteShader(fragment);gl.deleteShader(pickFragment);
  const vao=gl.createVertexArray(),position=gl.createBuffer(),index=gl.createBuffer(); if(!vao||!position||!index)throw new Error("Unable to allocate indexed province buffers");
  gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,position);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,index);gl.bindVertexArray(null);
  const loc=(p)=>({camera:gl.getUniformLocation(p,"u_camera"),half:gl.getUniformLocation(p,"u_halfExtent"),province:gl.getUniformLocation(p,"u_province"),selected:gl.getUniformLocation(p,"u_selected"),selectedColor:gl.getUniformLocation(p,"u_selectedColor")}); const visual=loc(program),pick=loc(pickProgram); let pack=null,visibleRanges=[];
  const setup=(p,l,camera,zoom)=>{gl.useProgram(p);gl.uniform2f(l.camera,Number(camera.x)||0,Number(camera.y)||0);gl.uniform2f(l.half,180/Math.max(zoom,.0001),90/Math.max(zoom,.0001));};
  const draw=(p,l)=>{let calls=0;for(const r of visibleRanges){const first=Number(r.firstIndex)||0,count=Number(r.indexCount)||0;if(count>0&&count%3===0&&first>=0&&first+count<=pack.indices.length){gl.uniform1ui(l.province,Number(r.provinceIndex)>>>0);gl.drawElements(gl.TRIANGLES,count,gl.UNSIGNED_INT,first*4);calls+=1;}}return calls;};
  return {upload(next){if(!next?.vertices||!next?.indices||!next?.provinces)throw new Error("Invalid indexed province pack");pack=next;gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,position);gl.bufferData(gl.ARRAY_BUFFER,pack.vertices,gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,index);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,pack.indices,gl.STATIC_DRAW);gl.bindVertexArray(null);},setVisibleRanges(r){visibleRanges=Array.isArray(r)?r:[];},render({camera={x:0,y:0},zoom=1,selectedProvinceIndex=0xffffffff}={}){if(!pack)return 0;gl.viewport(0,0,canvas.width,canvas.height);gl.bindVertexArray(vao);setup(program,visual,camera,zoom);gl.uniform1ui(visual.selected,Number(selectedProvinceIndex)>>>0);gl.uniform4f(visual.selectedColor,.84,.69,.30,1);const calls=draw(program,visual);gl.bindVertexArray(null);return calls;},renderPicking({camera={x:0,y:0},zoom=1}={}){if(!pack)return 0;gl.bindVertexArray(vao);setup(pickProgram,pick,camera,zoom);const calls=draw(pickProgram,pick);gl.bindVertexArray(null);return calls;},dispose(){gl.deleteBuffer(position);gl.deleteBuffer(index);gl.deleteVertexArray(vao);gl.deleteProgram(program);gl.deleteProgram(pickProgram);},gl};
}
function compile(gl,type,source){const s=gl.createShader(type);if(!s)throw new Error("GPU shader allocation failed");gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const log=gl.getShaderInfoLog(s)||"shader compile failed";gl.deleteShader(s);throw new Error(log);}return s;}
function link(gl,v,f){const p=gl.createProgram();if(!p)throw new Error("GPU program allocation failed");gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const log=gl.getProgramInfoLog(p)||"program link failed";gl.deleteProgram(p);throw new Error(log);}return p;}
