const EDGES = Object.freeze(["north", "east", "south", "west"]);
const OPPOSITE = Object.freeze({ north: "south", east: "west", south: "north", west: "east" });
function assertTile(tile) { if (!tile || !Number.isInteger(tile.x) || !Number.isInteger(tile.y) || !Number.isInteger(tile.zoom) || tile.zoom < 0) throw new Error("Invalid terrain tile key."); }
function key(zoom, x, y) { return `${zoom}/${x}/${y}`; }
function neighbor(tile, edge) { const d = edge === "north" ? [0,-1] : edge === "east" ? [1,0] : edge === "south" ? [0,1] : [-1,0]; return { x: tile.x + d[0], y: tile.y + d[1] }; }
function finerNeighborKeys(tile, edge) { const n = neighbor(tile, edge); const x = tile.x * 2; const y = tile.y * 2; if (edge === "north") return [[2 * n.x, 2 * n.y + 1], [2 * n.x + 1, 2 * n.y + 1]]; if (edge === "east") return [[2 * n.x, y], [2 * n.x, y + 1]]; if (edge === "south") return [[x, 2 * n.y], [x + 1, 2 * n.y]]; return [[2 * n.x + 1, y], [2 * n.x + 1, y + 1]]; }

export function buildTerrainAdjacency(tile, lookup) { assertTile(tile); if (!(lookup instanceof Map)) throw new Error("Terrain adjacency requires a tile lookup map."); const result = {}; for (const edge of EDGES) { const n = neighbor(tile, edge); const sameId = key(tile.zoom, n.x, n.y); if (lookup.has(sameId)) { result[edge] = lookup.get(sameId); continue; } if (tile.zoom > 0) { const parentId = key(tile.zoom - 1, Math.floor(n.x / 2), Math.floor(n.y / 2)); if (lookup.has(parentId)) { result[edge] = lookup.get(parentId); continue; } } if (tile.zoom < 30) { const children = finerNeighborKeys(tile, edge).map(([x, y]) => key(tile.zoom + 1, x, y)).map((id) => lookup.get(id)).filter(Boolean); if (children.length) { result[edge] = Object.freeze({ ...children[0], coverage: Object.freeze(children.map((child) => child.id).filter(Boolean)) }); continue; } } result[edge] = null; } return Object.freeze(result); }

export function planTerrainLodSeams(tileLod, adjacency) { if (!Number.isInteger(tileLod) || tileLod < 0) throw new Error("Tile LOD must be non-negative."); if (!adjacency || typeof adjacency !== "object") throw new Error("Terrain adjacency is required."); const plan = {}; for (const edge of EDGES) { const neighborLod = adjacency[edge]?.lod ?? tileLod; if (!Number.isInteger(neighborLod) || neighborLod < 0) throw new Error(`Invalid neighbor LOD on ${edge}.`); const delta = neighborLod - tileLod; if (Math.abs(delta) > 1) throw new Error(`Terrain LOD discontinuity exceeds one level on ${edge}.`); plan[edge] = Object.freeze({ neighborLod, delta, transition: delta === 0 ? "same" : delta > 0 ? "neighbor-finer" : "neighbor-coarser" }); } return Object.freeze(plan); }

export { EDGES, OPPOSITE };
