const EDGES=Object.freeze(["north","east","south","west"]);const MODES=Object.freeze(["same","neighbor-coarser","neighbor-finer","boundary"]);
function assertSize(size){if(!Number.isInteger(size)||size<3||size%2===0)throw new Error("Terrain grid size must be an odd integer >= 3 for 2:1 edge stitching.");} function assertMode(mode){if(!MODES.includes(mode))throw new Error(`Unknown terrain edge mode: ${mode}.`);} function v(x,y,n){return y*n+x;} function tri(out,a,b,c){out.push(a,b,c);} function baseGrid(n,edges){const out=[];const active=new Set(EDGES.filter(e=>edges[e]!=="same"&&edges[e]!=="boundary"));for(let y=0;y<n-1;y++)for(let x=0;x<n-1;x++){if(active.has("north")&&y===0)continue;if(active.has("south")&&y===n-2)continue;if(active.has("west")&&x===0)continue;if(active.has("east")&&x===n-2)continue;const a=v(x,y,n),b=v(x+1,y,n),c=v(x,y+1,n),d=v(x+1,y+1,n);tri(out,a,c,b);tri(out,b,c,d);}return out;}
function stitchNorth(out,n){for(let x=0;x<n-1;x+=2){const b0=v(x,0,n),b1=v(x+1,0,n),b2=v(x+2,0,n),i0=v(x,1,n),i1=v(x+1,1,n),i2=v(x+2,1,n);tri(out,b0,i0,b2);tri(out,b2,i0,i2);tri(out,b2,i2,b1);tri(out,b1,i2,i1);}}
function stitchSouth(out,n){const l=n-1;for(let x=0;x<l;x+=2){const b0=v(x,l,n),b1=v(x+1,l,n),b2=v(x+2,l,n),i0=v(x,l-1,n),i1=v(x+1,l-1,n),i2=v(x+2,l-1,n);tri(out,b0,b2,i0);tri(out,b2,i2,i0);tri(out,b2,b1,i2);tri(out,b1,i1,i2);}}
function stitchWest(out,n){for(let y=0;y<n-1;y+=2){const b0=v(0,y,n),b1=v(0,y+1,n),b2=v(0,y+2,n),i0=v(1,y,n),i1=v(1,y+1,n),i2=v(1,y+2,n);tri(out,b0,b2,i0);tri(out,b2,i2,i0);tri(out,b2,b1,i2);tri(out,b1,i1,i2);}}
function stitchEast(out,n){const l=n-1;for(let y=0;y<l;y+=2){const b0=v(l,y,n),b1=v(l,y+1,n),b2=v(l,y+2,n),i0=v(l-1,y,n),i1=v(l-1,y+1,n),i2=v(l-1,y+2,n);tri(out,b0,i0,b2);tri(out,b2,i0,i2);tri(out,b2,i2,b1);tri(out,b1,i2,i1);}}
function cornerMode(edges,a,b){const x=edges[a],y=edges[b];const transition=x!=="same"&&x!=="boundary"&&y!=="same"&&y!=="boundary";if(!transition)return null;if(x===y)return x;throw new Error(`Mixed adjacent terrain edge transitions require a dedicated corner topology: ${a}-${b}.`);}
function stitchCorner(out,n,corner,mode){const l=n-1;if(corner==="north-east"){const c=v(l,0,n),e=v(l-1,0,n),s=v(l,1,n);mode==="neighbor-coarser"?tri(out,c,s,e):tri(out,c,e,s);}else if(corner==="north-west"){const c=v(0,0,n),e=v(1,0,n),s=v(0,1,n);mode==="neighbor-coarser"?tri(out,c,e,s):tri(out,c,s,e);}else if(corner==="south-east"){const c=v(l,l,n),e=v(l, l-1,n),s=v(l-1,l,n);mode==="neighbor-coarser"?tri(out,c,e,s):tri(out,c,s,e);}else {const c=v(0,l,n),e=v(0,l-1,n),s=v(1,l,n);mode==="neighbor-coarser"?tri(out,c,s,e):tri(out,c,e,s);}}
function stitched(n,edges){const out=baseGrid(n,edges);for(const edge of EDGES){const mode=edges[edge];if(mode==="neighbor-coarser"){if(edge==="north")stitchNorth(out,n);else if(edge==="south")stitchSouth(out,n);else if(edge==="west")stitchWest(out,n);else stitchEast(out,n);}else if(mode==="neighbor-finer"){if(edge==="north")stitchNorth(out,n);else if(edge==="south")stitchSouth(out,n);else if(edge==="west")stitchWest(out,n);else stitchEast(out,n);}}
for(const [corner,a,b] of [["north-east","north","east"],["north-west","north","west"],["south-east","south","east"],["south-west","south","west"]]){const mode=cornerMode(edges,a,b);if(mode)stitchCorner(out,n,corner,mode);}return out;}
export function createTerrainEdgeIndexTopology({size,edges={}}={}){assertSize(size);for(const edge of EDGES)assertMode(edges[edge]??"same");const resolved=Object.freeze(Object.fromEntries(EDGES.map(edge=>[edge,edges[edge]??"same"])));const indices=stitched(size,resolved);const transitionEdges=EDGES.filter(edge=>resolved[edge]!=="same"&&resolved[edge]!=="boundary");return Object.freeze({size,vertexCount:size*size,indexCount:indices.length,indices:new Uint32Array(indices),edges:resolved,transitionEdges:Object.freeze(transitionEdges)});} export {EDGES,MODES};
