export function createProvinceModel({
  id,
  name,
  geometryId = null,
  region = null,
  terrain = null,
  owner = null,
  controller = null,
  governor = null,
  culture = null,
  religion = null,
  population = 0,
  development = 0,
  wealth = 0,
  supplyLimit = 0,
  historical = null,
  historicalDate = null,
  historicalSource = null,
  cities = [],
  roads = [],
  buildings = [],
  characters = [],
  armies = [],
  sea = false,
  river = false,
  port = false,
  fortLevel = 0,
  status = {
    underSiege: false,
    occupied: false,
    looted: false,
  },
}) {
  return Object.freeze({
    id,
    name,
    geometryId,
    region,
    terrain,
    owner,
    controller,
    governor,
    culture,
    religion,
    population,
    development,
    wealth,
    supplyLimit,
    historical,
    historicalDate,
    historicalSource,
    cities,
    roads,
    buildings,
    characters,
    armies,
    sea,
    river,
    port,
    fortLevel,
    status,
  });
}
