import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,"../..");
const read=(p)=>readFileSync(resolve(root,p),"utf8");
const renderer=read("src/map/rendering/gpu/BinaryMapRenderer.js");
const source=read("src/map/runtime/BinaryMapAssetSource.js");
const loader=read("src/map/runtime/MapBinLoader.js");
const contract=read("src/map/rendering/MapRendererContract.js");
const controller=read("src/map/runtime/MapRuntimeController.js");
const host=read("src/map/rendering/MapEngineV2.jsx");
const worldMap=read("src/map/components/WorldMap.jsx");
const soa=read("src/map/runtime/ProvinceSoA.js");
const spatial=read("src/map/runtime/SpatialIndex.js");
const camera=read("src/map/runtime/MapCameraRig.js");
for(const method of ["initialize","resize","setCamera","setSelectedProvinceId","setHoveredProvinceId","pick","render","start","stop","dispose"])assert.match(contract,new RegExp(`${method}\\(`));
assert.match(controller,/requestAnimationFrame/);assert.match(controller,/queueHover/);assert.match(controller,/renderer\.pick/);
assert.match(renderer,/extends MapRendererContract/);assert.match(renderer,/getContext\("webgl2"/);assert.match(renderer,/bufferData\(gl\.ARRAY_BUFFER,assetSource\.geometry/);assert.match(renderer,/texStorage2D\(gl\.TEXTURE_2D,1,gl\.RGBA8,1,1\)/);assert.match(renderer,/readPixels\(0,0,1,1/);assert.match(renderer,/new Uint8Array\(4\)/);assert.match(renderer,/deleteBuffer\(s\.buffer\)/);
assert.match(source,/new Uint32Array\(buffer,p,n\)/);assert.match(source,/new Float32Array\(buffer,p\+n\*8,n\)/);assert.match(source,/new Float32Array\(buffer,this.header.geometryOffset/);assert.match(source,/Object\.freeze\(this\.header\)/);
assert.match(loader,/fetchImpl\(url/);assert.match(loader,/response\.arrayBuffer\(\)/);assert.match(loader,/BinaryMapAssetSource\.fromArrayBuffer/);
assert.match(soa,/static fromBinary/);assert.match(soa,/soa\.ids = new Uint32Array\(buffer, base, count\)/);
assert.match(host,/loadMapBin/);assert.match(host,/loadMapBin\(assetUrl\)/);assert.doesNotMatch(host,/provinces/);assert.doesNotMatch(host,/BinaryMapAssetBuilder/);assert.doesNotMatch(host,/MapAssetBridge/);assert.doesNotMatch(host,/GpuMapRenderer/);assert.doesNotMatch(host,/onPointerMove/);
assert.doesNotMatch(worldMap,/useWorldMap/);assert.doesNotMatch(worldMap,/provinces/);
assert.match(spatial,/class QuadtreeIndex/);assert.match(camera,/pitchMin/);assert.match(camera,/yawMax/);
console.log("H2/H1 map contract passed: prebuilt mapbin loading, zero-copy SoA, direct WebGL geometry and imperative runtime ownership.");
