import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,"../..");
const read=(p)=>readFileSync(resolve(root,p),"utf8");
const renderer=read("src/map/rendering/gpu/BinaryMapRenderer.js");
const source=read("src/map/runtime/BinaryMapAssetSource.js");
const builder=read("src/map/runtime/BinaryMapAssetBuilder.js");
const contract=read("src/map/rendering/MapRendererContract.js");
const controller=read("src/map/runtime/MapRuntimeController.js");
const host=read("src/map/rendering/MapEngineV2.jsx");
const soa=read("src/map/runtime/ProvinceSoA.js");
const spatial=read("src/map/runtime/SpatialIndex.js");
const camera=read("src/map/runtime/MapCameraRig.js");
for(const method of ["initialize","resize","setCamera","setSelectedProvinceId","setHoveredRasterId","pick","render","dispose"])assert.match(contract,new RegExp(`${method}\\(`));
assert.match(controller,/requestAnimationFrame/);assert.match(controller,/queueHover/);assert.match(controller,/renderer\.pick/);
assert.match(renderer,/extends MapRendererContract/);assert.match(renderer,/getContext\("webgl2"/);assert.match(renderer,/bufferData\(gl\.ARRAY_BUFFER,assetSource\.geometry/);assert.match(renderer,/texStorage2D\(gl\.TEXTURE_2D,1,gl\.RGBA8,1,1\)/);assert.match(renderer,/readPixels\(0,0,1,1/);assert.match(renderer,/new Uint8Array\(4\)/);assert.match(renderer,/deleteBuffer\(s\.buffer\)/);
assert.match(source,/new Uint32Array\(buffer,p,n\)/);assert.match(source,/new Float32Array\(buffer,p\+n\*8,n\)/);assert.match(source,/new Float32Array\(buffer,this.header.geometryOffset/);assert.match(source,/Object\.freeze\(this\.header\)/);
assert.match(builder,/buildMapBinFromProvinces/);assert.match(builder,/tiles\.push\(start,valid\.length,i/);
assert.match(soa,/static fromBinary/);assert.match(soa,/soa\.ids=new Uint32Array\(buffer,base,count\)/);
assert.match(host,/BinaryMapAssetSource/);assert.match(host,/BinaryMapRenderer/);assert.doesNotMatch(host,/MapAssetBridge/);assert.doesNotMatch(host,/GpuMapRenderer/);assert.doesNotMatch(host,/onPointerMove/);assert.doesNotMatch(host,/rendererRef/);assert.match(spatial,/class QuadtreeIndex/);assert.match(camera,/pitchMin/);assert.match(camera,/yawMax/);
console.log("Map Engine v2 contract passed: binary map asset source, direct WebGL geometry, imperative runtime and persistent 1x1 picking target.");
