import assert from "node:assert/strict";
import { encodeTerrainTile, decodeTerrainTile } from "../../src/map/rendering/terrain/TerrainAssetCodec.js";
import { buildTerrainGridMesh } from "../../src/map/rendering/terrain/TerrainGeometry.js";
import { buildTerrainMvp } from "../../src/map/rendering/terrain/TerrainCameraMath.js";
import { parseTileList, copernicusSourceTileKeysForBounds, copernicusTileKey } from "../asset-builder/dem/CopernicusDemSource.js";
import { coordinateInCoverage, terrainTileBoundsForCoverage } from "../asset-builder/pipelines/TerrainPipeline.js";
import { makeTerrainTileKey } from "../../src/map/rendering/terrain/TerrainTile.js";
import { TERRAIN_LODS } from "../../src/map/rendering/terrain/TerrainLod.js";

const size = 3;
const heights = Float32Array.from([0,200,400,100,500,800,0,600,1000]);
const normals = new Int8Array(size * size * 3); normals.fill(127);
const splatRgba = new Uint8Array(size * size * 4); splatRgba.fill(255);
const splatSnow = new Uint8Array(size * size); splatSnow.fill(0);
const landMask = new Uint8Array(size * size); landMask.fill(255);
const demValidity = new Uint8Array(size * size); demValidity.fill(255);
const bytes = encodeTerrainTile({ size, heights, normals, splatRgba, splatSnow, landMask, demValidity, bounds: { minX: 30, minY: 35, maxX: 40, maxY: 45 } });
const decoded = decodeTerrainTile(bytes);
assert.equal(decoded.version, 2);
assert.equal(decoded.size, size);
assert.deepEqual(Array.from(decoded.heights), Array.from(heights));
assert.deepEqual(Array.from(decoded.demValidity), Array.from(demValidity));
assert.equal(decoded.bounds.minX, 30);
assert.equal(decoded.bounds.maxY, 45);
const mesh = buildTerrainGridMesh({ heights, size, skirtDepth: 50 });
assert.equal(mesh.vertexHeights.length, size * size + (size - 1) * 8);
assert.equal(mesh.indices.length, (size - 1) * (size - 1) * 6 + (size - 1) * 4 * 6);
assert.equal(mesh.vertexHeights[size * size], heights[0] - 50);
assert.ok(buildTerrainMvp({ x: 0, y: 0, zoom: 2, pitch: 24, yaw: 8 }, 1920, 1080).every(Number.isFinite));
assert.equal(copernicusTileKey(38.2, 27.7), "Copernicus_DSM_COG_10_N38_00_E027_00_DEM");
assert.equal(copernicusTileKey(-12.2, -7.7), "Copernicus_DSM_COG_10_S13_00_W008_00_DEM");
const index = parseTileList("foo/Copernicus_DSM_COG_10_N38_00_E027_00_DEM/\nbar/Copernicus_DSM_COG_10_S13_00_W008_00_DEM/");
assert.deepEqual(index, ["Copernicus_DSM_COG_10_N38_00_E027_00_DEM", "Copernicus_DSM_COG_10_S13_00_W008_00_DEM"]);
const coverage = [26, 35, 46, 43];
const sourceTiles = copernicusSourceTileKeysForBounds(coverage);
assert.equal(sourceTiles.length, 160);
assert.equal(sourceTiles[0], "Copernicus_DSM_COG_10_N35_00_E026_00_DEM");
assert.equal(sourceTiles.at(-1), "Copernicus_DSM_COG_10_N42_00_E045_00_DEM");
assert.equal(new Set(sourceTiles).size, 160);
assert.equal(sourceTiles.some((key) => key.includes("N75") || key.includes("W082") || key.includes("E163")), false);
assert.equal(coordinateInCoverage(26, 35, coverage), true);
assert.equal(coordinateInCoverage(46, 43, coverage), true);
assert.equal(coordinateInCoverage(25.999999, 40, coverage), false);
assert.equal(coordinateInCoverage(40, 43.000001, coverage), false);
assert.equal(coordinateInCoverage(109, 75, coverage), false);
const clippedLod0 = terrainTileBoundsForCoverage(makeTerrainTileKey(0, 0, 0), coverage);
assert.deepEqual(clippedLod0, { minX: 26, minY: 35, maxX: 46, maxY: 43 });
const clippedLod3 = terrainTileBoundsForCoverage(makeTerrainTileKey(3, 4, 5), coverage);
assert.deepEqual(clippedLod3, { minX: 26, minY: 35, maxX: 45, maxY: 43 });
assert.ok(clippedLod3.minX >= coverage[0] && clippedLod3.maxX <= coverage[2]);
assert.ok(clippedLod3.minY >= coverage[1] && clippedLod3.maxY <= coverage[3]);
assert.ok(clippedLod3.minX < clippedLod3.maxX && clippedLod3.minY < clippedLod3.maxY);
assert.equal(TERRAIN_LODS.length, 5);
console.log("terrain-dem-pipeline.test.js: PASS");
