import assert from "node:assert/strict";
import { TERRAIN_LODS, terrainLodForDistance } from "../../src/map/rendering/terrain/TerrainLod.js";
import { makeTerrainTileKey, terrainTileBounds } from "../../src/map/rendering/terrain/TerrainTile.js";
import { planTerrainStreaming, terrainTileZoomForLod } from "../../src/map/rendering/terrain/TerrainStreaming.js";
import { normalizeSplatWeights } from "../../src/map/rendering/terrain/TerrainMaterial.js";
import { buildTerrainGridMesh } from "../../src/map/rendering/terrain/TerrainGeometry.js";
import { addTerrainSkirts, terrainLodEdgeCompatible } from "../../src/map/rendering/terrain/TerrainSeams.js";
import { buildTerrainEdgeSignature, clipTerrainSampleToLand } from "../../src/map/rendering/terrain/TerrainTopology.js";
import { createTerrainTileManifest, validateTerrainTileManifest } from "../../src/map/rendering/terrain/TerrainTileManifest.js";
assert.deepEqual(TERRAIN_LODS.map(l=>l.level),[0,1,2,3,4]);assert.equal(terrainLodForDistance(300),0);assert.equal(terrainLodForDistance(100),1);assert.equal(terrainLodForDistance(40),2);assert.equal(terrainLodForDistance(12),3);assert.equal(terrainLodForDistance(2),4);
const tile=makeTerrainTileKey(2,-1,2);assert.equal(tile.id,"2/3/2");assert.deepEqual(terrainTileBounds(tile),{minX:90,minY:0,maxX:180,maxY:45});assert.equal(terrainTileZoomForLod(4),5);
const plan=planTerrainStreaming({viewBounds:{minX:20,minY:30,maxX:70,maxY:55},cameraDistance:40,maxTiles:32});assert.equal(plan.lod,2);assert.equal(plan.zoom,2);assert.ok(plan.tileCount>0);
assert.ok(Math.abs(normalizeSplatWeights([1,2,3,4,0]).reduce((s,v)=>s+v,0)-1)<1e-9);assert.deepEqual(normalizeSplatWeights([0,0,0,0,0]),[0,0,1,0,0]);
const heights=Float32Array.from([0,.1,0,.2,.3,.2,0,.2,0]),mesh=buildTerrainGridMesh({heights,size:3});assert.equal(mesh.indices.length,72);assert.equal(mesh.positions.length,50);assert.equal(mesh.vertexHeights.length,25);assert.equal(terrainLodEdgeCompatible(129,65),true);
const invalidCenter=Uint8Array.from([255,255,255,255,0,255,255,255,255]),culled=buildTerrainGridMesh({heights,validity:invalidCenter,size:3,skirtDepth:0});assert.equal(culled.indices.length,0);assert.equal(culled.vertexValidity[4],0);
const basePositions=new Float32Array(27),baseUvs=new Float32Array(18),baseNormals=new Float32Array(27),baseIndices=new Uint32Array(24);for(let i=0;i<9;i+=1){basePositions[i*3]=i%3;basePositions[i*3+1]=Math.floor(i/3);basePositions[i*3+2]=heights[i];baseUvs[i*2]=(i%3)/2;baseUvs[i*2+1]=Math.floor(i/3)/2;baseNormals[i*3+2]=1;}let cursor=0;for(let y=0;y<2;y+=1)for(let x=0;x<2;x+=1){const a=y*3+x,b=a+1,c=a+3,d=c+1;baseIndices[cursor++]=a;baseIndices[cursor++]=c;baseIndices[cursor++]=b;baseIndices[cursor++]=b;baseIndices[cursor++]=c;baseIndices[cursor++]=d;}const skirted=addTerrainSkirts({positions:basePositions,uvs:baseUvs,normals:baseNormals,indices:baseIndices},{size:3,depth:.03});assert.equal(skirted.positions.length,63);assert.equal(skirted.indices.length,72);
const landMask={contains:(x,y)=>x>=0&&y>=0};assert.equal(clipTerrainSampleToLand({x:1,y:2,height:3,landMask}).land,true);const edge=buildTerrainEdgeSignature({tile,heights,size:3});assert.equal(edge.top.length,3);
const manifest=createTerrainTileManifest({tile,bounds:terrainTileBounds(tile),assets:{heightmap:"terrain/2/3/2/height.r16",normal:"terrain/2/3/2/normal.ktx2",splatRgba:"terrain/2/3/2/splat-rgba.ktx2",splatSnow:"terrain/2/3/2/splat-snow.ktx2",landMask:"terrain/2/3/2/land-mask.ktx2"}});assert.equal(validateTerrainTileManifest(manifest),true);
console.log("Phase E terrain contracts: PASS");
