import assert from "node:assert/strict";
import { WebGPUMapRenderer, CULL_WGSL, RENDER_WGSL, PICK_WGSL } from "../../src/map/rendering/gpu/WebGPUMapRenderer.js";
import { MapRendererContract, assertRendererContract } from "../../src/map/rendering/MapRendererContract.js";

const renderer = new WebGPUMapRenderer({});
assertRendererContract(renderer);
assert(renderer instanceof MapRendererContract);
assert.match(CULL_WGSL, /@compute @workgroup_size\(64\)/);
assert.match(CULL_WGSL, /viewProj: mat4x4<f32>/);
assert.match(CULL_WGSL, /c\.x>=-c\.w/);
assert.match(CULL_WGSL, /c\.z<=c\.w/);
assert.match(CULL_WGSL, /camera\.zoom>=64\.0/);
assert.match(CULL_WGSL, /camera\.zoom>=16\.0/);
assert.match(CULL_WGSL, /camera\.zoom>=4\.0/);
assert.match(CULL_WGSL, /var<storage, read> tiles/);
assert.match(CULL_WGSL, /var<storage, read> lods/);
assert.match(CULL_WGSL, /var<storage, read> bounds/);
assert.match(CULL_WGSL, /var<storage, read_write> indirect/);
assert.match(RENDER_WGSL, /@vertex/);
assert.match(RENDER_WGSL, /viewProj/);
assert.match(PICK_WGSL, /@fragment/);
const source = { provinceCount: 1, tileCount: 1, ids: new Uint32Array([7]), minX: new Float32Array([0]), minY: new Float32Array([0]), maxX: new Float32Array([1]), maxY: new Float32Array([1]), geometry: new Float32Array([0,0,1,0,0,1]), tileIndex: new Uint32Array([0,3,0,0,0,0]), lodRanges: new Uint32Array([0,1,0,0]) , getProvinceGeometryRange: () => ({ tileOffset: 0, tileCount: 1 }), indexOf: () => 0 };
assert.equal(WebGPUMapRenderer.isSupported(), false);
const initialized = await renderer.initialize({ assetSource: source });
assert.equal(initialized, false);
renderer.dispose();
console.log("WebGPU H3.3-H3.5 contract passed: matrix frustum planes, zoom LOD selection, indirect buffer bindings, render pipeline and async pick resources are defined with safe unsupported-device fallback.");
