const MAGIC = 0x484D4150;
const VERSION = 1;
const HEADER_BYTES = 64;
const PROVINCE_FIELD_COUNT = 8;
const TILE_STRIDE = 6;
const LOD_STRIDE = 4;
const CITY_STRIDE = 6;
const HEADER = Object.freeze({ magic:0, version:4, flags:6, provinceCount:8, tileCount:12, geometryPointCount:16, lodRangeCount:20, cityCount:24, provinceOffset:28, tileOffset:32, geometryOffset:36, lodOffset:40, cityOffset:44, paletteOffset:48, paletteByteLength:52, totalByteLength:56 });

/** Immutable zero-copy view over a versioned .mapbin ArrayBuffer. */
export class BinaryMapAssetSource {
  constructor(buffer){
    if(!(buffer instanceof ArrayBuffer))throw new TypeError("BinaryMapAssetSource requires an ArrayBuffer");
    if(buffer.byteLength<HEADER_BYTES)throw new RangeError("Invalid mapbin: truncated header");
    this.buffer=buffer;this.header=readHeader(buffer);validateHeader(this.header,buffer.byteLength);
    const p=this.header.provinceOffset,n=this.header.provinceCount;
    this.ids=new Uint32Array(buffer,p,n);this.owner=new Uint32Array(buffer,p+n*4,n);this.minX=new Float32Array(buffer,p+n*8,n);this.minY=new Float32Array(buffer,p+n*12,n);this.maxX=new Float32Array(buffer,p+n*16,n);this.maxY=new Float32Array(buffer,p+n*20,n);this.centerX=new Float32Array(buffer,p+n*24,n);this.centerY=new Float32Array(buffer,p+n*28,n);
    this.tileIndex=new Uint32Array(buffer,this.header.tileOffset,this.header.tileCount*TILE_STRIDE);this.geometry=new Float32Array(buffer,this.header.geometryOffset,this.header.geometryPointCount*2);this.lodRanges=new Uint32Array(buffer,this.header.lodOffset,this.header.lodRangeCount*LOD_STRIDE);this.cityBlocks=new Float32Array(buffer,this.header.cityOffset,this.header.cityCount*CITY_STRIDE);this.palette=new Uint8Array(buffer,this.header.paletteOffset,this.header.paletteByteLength);
    this.idToIndex=new Map();for(let i=0;i<n;i+=1)this.idToIndex.set(String(this.ids[i]),i);Object.freeze(this.header);
  }
  static fromArrayBuffer(buffer){return new BinaryMapAssetSource(buffer);}
  get provinceCount(){return this.header.provinceCount;} get tileCount(){return this.header.tileCount;} get geometryPointCount(){return this.header.geometryPointCount;}
  getProvinceId(index){return this.ids[index]??0;}
  getProvinceGeometryRange(index,lod=0){if(index<0||index>=this.provinceCount)return null;const selected=index+lod;if(selected>=this.header.lodRangeCount)return null;const b=selected*LOD_STRIDE;return{tileOffset:this.lodRanges[b],tileCount:this.lodRanges[b+1]};}
  geometryView(pointOffset,pointCount){if(pointOffset<0||pointCount<0||pointOffset+pointCount>this.geometryPointCount)throw new RangeError("Geometry range out of bounds");return new Float32Array(this.buffer,this.header.geometryOffset+pointOffset*8,pointCount*2);}
  tileRecord(index){return this.tileIndex.subarray(index*TILE_STRIDE,index*TILE_STRIDE+TILE_STRIDE);} lodRecord(index){return this.lodRanges.subarray(index*LOD_STRIDE,index*LOD_STRIDE+LOD_STRIDE);} cityRecord(index){return this.cityBlocks.subarray(index*CITY_STRIDE,index*CITY_STRIDE+CITY_STRIDE);} indexOf(id){return this.idToIndex.get(String(id))??-1;}
  static fromProvinceEntries(entries=[]){const n=entries.length,ids=new Uint32Array(n),owner=new Uint32Array(n),minX=new Float32Array(n),minY=new Float32Array(n),maxX=new Float32Array(n),maxY=new Float32Array(n),centerX=new Float32Array(n),centerY=new Float32Array(n),geometry=[],lod=[],tiles=[];for(let i=0;i<n;i+=1){const e=entries[i];ids[i]=numericId(e?.province?.id,i+1);owner[i]=numericId(e?.country?.id,0);const points=[];for(const poly of e?.geometry?.polygons??[])for(const pt of poly??[]){const x=Number(pt?.[0]),y=Number(pt?.[1]);if(Number.isFinite(x)&&Number.isFinite(y))points.push([x,y]);}const b=bounds(points);minX[i]=b.minX;minY[i]=b.minY;maxX[i]=b.maxX;maxY[i]=b.maxY;centerX[i]=(b.minX+b.maxX)*.5;centerY[i]=(b.minY+b.maxY)*.5;const po=geometry.length/2;for(const [x,y] of points)geometry.push(x,y);lod.push(tiles.length/TILE_STRIDE,0,0,0);tiles.push(po,points.length,i,0,0,0);lod[lod.length-3]=1;}const palette=new Uint8Array(Math.max(4,(n+1)*4));entries.forEach((e,i)=>palette.set(color(e?.country?.color),(i+1)*4));return pack({ids,owner,minX,minY,maxX,maxY,centerX,centerY,geometry,lod,tiles,palette});}
}
export function buildBinaryMapAssetSource(entries){return BinaryMapAssetSource.fromArrayBuffer(BinaryMapAssetSource.fromProvinceEntries(entries));}
function pack(d){const n=d.ids.length,pb=n*PROVINCE_FIELD_COUNT*4,tb=d.tiles.length*4,gb=d.geometry.length*4,lb=d.lod.length*4,po=HEADER_BYTES+pb+tb+gb+lb,total=po+d.palette.byteLength,b=new ArrayBuffer(total),v=new DataView(b);v.setUint32(0,MAGIC,true);v.setUint16(4,VERSION,true);v.setUint32(8,n,true);v.setUint32(12,d.tiles.length/TILE_STRIDE,true);v.setUint32(16,d.geometry.length/2,true);v.setUint32(20,d.lod.length/LOD_STRIDE,true);v.setUint32(28,HEADER_BYTES,true);v.setUint32(32,HEADER_BYTES+pb,true);v.setUint32(36,HEADER_BYTES+pb+tb,true);v.setUint32(40,HEADER_BYTES+pb+tb+gb,true);v.setUint32(44,po,true);v.setUint32(48,po,true);v.setUint32(52,d.palette.byteLength,true);v.setUint32(56,total,true);let o=HEADER_BYTES;for(const f of[d.ids,d.owner]){new Uint32Array(b,o,f.length).set(f);o+=f.byteLength;}for(const f of[d.minX,d.minY,d.maxX,d.maxY,d.centerX,d.centerY]){new Float32Array(b,o,f.length).set(f);o+=f.byteLength;}new Uint32Array(b,o,d.tiles.length).set(d.tiles);o+=tb;new Float32Array(b,o,d.geometry.length).set(d.geometry);o+=gb;new Uint32Array(b,o,d.lod.length).set(d.lod);new Uint8Array(b,po,d.palette.byteLength).set(d.palette);return b;}
function readHeader(b){const v=new DataView(b);return{magic:v.getUint32(0,true),version:v.getUint16(4,true),flags:v.getUint16(6,true),provinceCount:v.getUint32(8,true),tileCount:v.getUint32(12,true),geometryPointCount:v.getUint32(16,true),lodRangeCount:v.getUint32(20,true),cityCount:v.getUint32(24,true),provinceOffset:v.getUint32(28,true),tileOffset:v.getUint32(32,true),geometryOffset:v.getUint32(36,true),lodOffset:v.getUint32(40,true),cityOffset:v.getUint32(44,true),paletteOffset:v.getUint32(48,true),paletteByteLength:v.getUint32(52,true),totalByteLength:v.getUint32(56,true)};}
function validateHeader(h,bytes){if(h.magic!==MAGIC)throw new Error("Invalid mapbin magic");if(h.version!==VERSION)throw new Error(`Unsupported mapbin version: ${h.version}`);if(h.totalByteLength!==bytes)throw new Error("Invalid mapbin length");const end=h.provinceOffset+h.provinceCount*PROVINCE_FIELD_COUNT*4;if(h.provinceOffset<HEADER_BYTES||h.provinceOffset%4||end>bytes||h.tileOffset<end||h.geometryOffset<h.tileOffset||h.lodOffset<h.geometryOffset||h.paletteOffset<h.lodOffset||h.paletteOffset>bytes)throw new Error("Invalid mapbin section offsets");}
function bounds(p){if(!p.length)return{minX:0,minY:0,maxX:0,maxY:0};let minX=p[0][0],minY=p[0][1],maxX=minX,maxY=minY;for(const[x,y]of p){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}return{minX,minY,maxX,maxY};}function numericId(v,f){const n=Number(v);return Number.isFinite(n)&&n>=0?n>>>0:f;}function color(v){const h=String(v??"6f765f").replace(/^#/,'');if(!/^[0-9a-f]{6}$/i.test(h))return[111,118,95,255];return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255];}
export const MAPBIN_LAYOUT=Object.freeze({MAGIC,VERSION,HEADER_BYTES,PROVINCE_FIELD_COUNT,TILE_STRIDE,LOD_STRIDE,CITY_STRIDE});
export default BinaryMapAssetSource;
