import { decodeGpuProvincePack } from "../rendering/gpu/GpuProvincePackFormat.js";
import { createGpuPickingFramebuffer, readProvinceId } from "../rendering/gpu/GpuProvincePicking.js";
import { createGpuBackend, backendCapabilities } from "./GpuBackendRouter.js";

export class GpuMapEngine {
  constructor(canvas, { fetchImpl = globalThis.fetch } = {}) { this.canvas=canvas; this.fetchImpl=fetchImpl; this.backend=null; this.pack=null; this.pickingTarget=null; this.camera={x:0,y:0,zoom:1}; this.selectedProvinceIndex=-1; }
  async loadPack(url) { if(typeof this.fetchImpl!=="function")throw new Error("GPU MapEngine requires fetch"); const response=await this.fetchImpl(url); if(!response.ok)throw new Error(`Unable to load HGPU pack: ${response.status}`); this.pack=decodeGpuProvincePack(await response.arrayBuffer()); this.backend=await createGpuBackend(this.canvas,this.pack); if(this.backend.kind==="webgl2"){this.backend.renderer.upload(this.pack);this.pickingTarget=createGpuPickingFramebuffer(this.backend.renderer.gl,this.canvas.width,this.canvas.height);} return this.pack; }
  async render(camera=this.camera) { this.camera={...camera}; if(!this.backend||!this.pack)return{backend:null,drawCalls:0,visible:0,lod:0}; const lod=lodForZoom(camera.zoom); if(this.backend.kind==="webgpu"){const result=await this.backend.renderer.render({centerX:camera.x,centerY:camera.y,zoom:camera.zoom});return{backend:"webgpu",drawCalls:result.indirectDraws,visible:this.pack.provinces.length,lod};} const candidates=this.pack.provinces.filter((p)=>intersects(p.bounds,camera,this.canvas.width,this.canvas.height)); this.backend.renderer.setVisibleRanges(candidates.map((p)=>({provinceIndex:p.provinceIndex,...p.lodRanges[lod]}))); const drawCalls=this.backend.renderer.render({camera,zoom:camera.zoom,selectedProvinceIndex:this.selectedProvinceIndex<0?0xffffffff:this.selectedProvinceIndex}); return{backend:"webgl2",drawCalls,visible:candidates.length,lod}; }
  pick(x,y){if(this.backend?.kind!=="webgl2"||!this.pickingTarget)return-1;this.backend.renderer.renderPicking({camera:this.camera,zoom:this.camera.zoom});this.selectedProvinceIndex=readProvinceId(this.backend.renderer.gl,this.pickingTarget,x,y);return this.selectedProvinceIndex;}
  capabilities(){return backendCapabilities(this.backend?.kind);}
  resize(width,height){this.canvas.width=width;this.canvas.height=height;if(this.backend?.kind==="webgl2"){const gl=this.backend.renderer.gl;if(this.pickingTarget){gl.deleteFramebuffer(this.pickingTarget.framebuffer);gl.deleteTexture(this.pickingTarget.texture);}this.pickingTarget=createGpuPickingFramebuffer(gl,width,height);}}
  dispose(){if(this.pickingTarget){this.backend?.renderer?.gl?.deleteFramebuffer(this.pickingTarget.framebuffer);this.backend?.renderer?.gl?.deleteTexture(this.pickingTarget.texture);}this.backend?.renderer?.destroy?.();this.backend=null;this.pack=null;}
}
function lodForZoom(zoom){const z=Number(zoom)||1;return z<2.5?0:z<8?1:z<24?2:3;}
function intersects(bounds,camera,width,height){if(!bounds)return false;const zoom=Math.max(.001,Number(camera.zoom)||1);const aspect=Math.max(.1,width/Math.max(1,height));const halfW=180/zoom;const halfH=(90/zoom)/aspect;return bounds.maxX>=camera.x-halfW&&bounds.minX<=camera.x+halfW&&bounds.maxY>=camera.y-halfH&&bounds.minY<=camera.y+halfH;}
